from Algorithms.Selection_sort import selecition_sorted
from Algorithms.Bubble_sort1 import bubble_sort
from Algorithms.Bogo_sort import bogo_sort
from Algorithms.inseriton_sort import insertion_sort
from Algorithms.Marge_sort import morgen_sort
from Algorithms.Bucket_sort import Bucket_sort
from Algorithms.Quick_sort import quick_sort
from Algorithms.Radix_sort import radix_sort
from Algorithms.MaxHeap_sort import max_heap_sort
from Algorithms.Counting_sort import counting_sort
from Algorithms.Shake_sort import shake_sort
from Algorithms.Stooge_sort import stooge_sort
